[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
wager_protocol = "4jHsbdQ3VvtrxzGC1Mx7bNYGrdKge2imTDAqJC2QHYsB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./env/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
